define({
    'delete': 'Delete',
    'edit': 'Edit',
    'form.body': 'Body',
    'form.conflict': 'This data is your saved data, not the current one. Click here to see it.',
    'form.required': 'This field is required',
    'form.title': 'Title',
    'help': 'Help',
    'help.h': 'display this help',
    'help.l': 'list all documents',
    'help.n': 'add a new document',
    'language': 'Language',
    'language.en': 'English',
    'language.fr': 'French',
    'message.delete': 'Document "%title%" has been deleted.',
    'message.save': 'Document "%title%" has been saved.',
    'error.internal_server_error': 'Something went wrong while trying to fetch data.',
    'new': 'New document',
    'save': 'Save',
    'title.edit': 'Editing %title%',
    'title.list': 'My Documents',
    'title.new': 'New Document',
    'prev': 'prev',
    'next': 'next'
});
