define({
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'form.body': 'Contenu',
    'form.conflict': 'Cette information a été sauvegardée, ce n\'est pas l\'actuelle. Cliquer ici pour la voir.',
    'form.required': 'Cette information est obligatoire',
    'form.title': 'Titre',
    'help': 'Aide',
    'help.h': 'afficher cette aide',
    'help.l': 'lister tous vos documents',
    'help.n': 'ajouter un nouveau document',
    'language': 'Langue',
    'language.en': 'Anglais',
    'language.fr': 'Français',
    'message.delete': 'Le document "%title%" a bien été supprimé.',
    'message.save': 'Le document "%title%" a bien été enregistré.',
    'error.internal_server_error': 'Un problème est survenu lors de la tentative de récupération des données :(',
    'new': 'Nouveau document',
    'save': 'Enregistrer',
    'title.edit': 'Edition de %title%',
    'title.list': 'Mes Documents',
    'title.new': 'Nouveau Document'
});
