define({
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'form.title': 'Titre',
    'form.body': 'Contenu',
    'help': 'Aide',
    'help.h': 'affiche cette aide',
    'help.l': 'liste tous vos documents',
    'help.n': 'ajouter un nouveau document',
    'language': 'Langue',
    'language.en': 'Anglais',
    'language.fr': 'Français',
    'message.delete': 'Le document "%title%" a bien été supprimé.',
    'message.save': 'Le document "%title%" a bien été enregistré.',
    'new': 'Nouveau document',
    'save': 'Enregistrer',
    'title.edit': 'Edition de %title%',
    'title.list': 'Mes Documents',
    'title.new': 'Nouveau Document'
});
