<?php
// This file generated by Propel 1.6.5-dev convert-conf target
return array (
  'Propilex\\Model\\Document' => 'Propilex/Model/Document.php',
  'Propilex\\Model\\DocumentPeer' => 'Propilex/Model/DocumentPeer.php',
  'Propilex\\Model\\DocumentQuery' => 'Propilex/Model/DocumentQuery.php',
  'Propilex\\Model\\map\\DocumentTableMap' => 'Propilex/Model/map/DocumentTableMap.php',
  'Propilex\\Model\\om\\BaseDocument' => 'Propilex/Model/om/BaseDocument.php',
  'Propilex\\Model\\om\\BaseDocumentPeer' => 'Propilex/Model/om/BaseDocumentPeer.php',
  'Propilex\\Model\\om\\BaseDocumentQuery' => 'Propilex/Model/om/BaseDocumentQuery.php',
);