<?php
// This file generated by Propel 1.6.5-dev convert-conf target
// from XML runtime conf file /Users/william/projects/Propilex/app/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'propilex' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=127.0.0.1;dbname=propilex',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'propilex',
  ),
  'generator_version' => '1.6.5-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-Propilex-conf.php');
return $conf;